family: "${ECS_WEB_TASK}"
networkMode: awsvpc
cpu: "${ECS_CPU_UNITS}"
memory: "${ECS_MEMORY_UNITS}"
executionRoleArn: "${ROLE_ARN}"
taskRoleArn: "${ROLE_ARN}"
requiresCompatibilities:
  - FARGATE
ephemeralStorage:
  sizeInGiB: 100
volumes:
  - name: data
    efsVolumeConfiguration:
      fileSystemId: "${EFS_FILESYSTEM_ID}"
      authorizationConfig:
        accessPointId: "${EFS_ACCESS_POINT_ID}"
        iam: ENABLED
      transitEncryption: ENABLED
containerDefinitions:
  - name: logs
    image: public.ecr.aws/aws-observability/aws-for-fluent-bit:stable
    firelensConfiguration:
      type: fluentbit
      options:
        enable-ecs-log-metadata: "true"
    memoryReservation: 50
    logConfiguration:
      logDriver: awslogs
      options:
        awslogs-group: "/analysistools/${TIER}/${APP}/web"
        awslogs-region: "${AWS_REGION}"
        awslogs-stream-prefix: logs

  - name: frontend
    image: "${FRONTEND_IMAGE_LATEST}"
    portMappings:
      - protocol: tcp
        containerPort: ${FRONTEND_CONTAINER_PORT}
    environment:
      - name: API_BASE_URL
        value: http://localhost:${BACKEND_CONTAINER_PORT}
      - name: API_EXTRACTION_URL
        value: http://localhost:${BACKEND_CONTAINER_PORT}
    secrets:
      - name: APP_PATH
        valueFrom: "/analysistools/${TIER}/${APP}/application_path"
      - name: SERVER_TIMEOUT
        valueFrom: "/analysistools/${TIER}/${APP}/server_timeout"
      - name: EXTRACTION_FORM_LIMIT
        valueFrom: "/analysistools/${TIER}/${APP}/extraction_form_limit"
    logConfiguration:
      logDriver: awsfirelens
      options:
        Name: datadog
        tls: "on"
        tls.verify: "off"
        dd_service: "${TIER}-${APP}-frontend"
        dd_source: "httpd"
        dd_tags: "project:${APP} tier:${TIER}"
        provider: ecs
      secretOptions:
        - name: Host
          valueFrom: /analysistools/${TIER}/datadog/log_endpoint_host
        - name: apikey
          valueFrom: /analysistools/${TIER}/datadog/api_key
    memoryReservation: 100
  - name: backend
    image: "${BACKEND_IMAGE_LATEST}"
    environment:
      - name: AWS_DEFAULT_REGION
        value: "${AWS_REGION}"
      - name: APP_NAME
        value: "${APP}"
      - name: EXTRACTION_APP_NAME
        value: "${APP}-extraction"
      - name: APP_PORT
        value: "${BACKEND_CONTAINER_PORT}"
      - name: APP_TIER
        value: "${TIER}"
      - name: WORKER_TYPE
        value: "fargate"
      - name: EXTRACTION_WORKER_TYPE
        value: "${EXTRACTION_WORKER_TYPE}"
      - name: LOG_LEVEL
        value: "${LOG_LEVEL}"
    secrets:
      - name: SERVER_TIMEOUT
        valueFrom: "/analysistools/${TIER}/${APP}/server_timeout"
      - name: API_BASE_URL
        valueFrom: "/analysistools/${TIER}/${APP}/base_url"
      - name: APP_BASE_URL
        valueFrom: "/analysistools/${TIER}/${APP}/base_url"
      - name: DATA_FOLDER
        valueFrom: "/analysistools/${TIER}/${APP}/data_folder"
      - name: INPUT_FOLDER
        valueFrom: "/analysistools/${TIER}/${APP}/input_folder"
      - name: OUTPUT_FOLDER
        valueFrom: "/analysistools/${TIER}/${APP}/output_folder"
      - name: DATA_BUCKET
        valueFrom: "/analysistools/${TIER}/${APP}/data_bucket"
      - name: DATA_BUCKET_PREFIX
        valueFrom: "/analysistools/${TIER}/${APP}/data_bucket_prefix"
      - name: IO_BUCKET
        valueFrom: "/analysistools/${TIER}/${APP}/data_bucket"
      - name: INPUT_KEY_PREFIX
        valueFrom: "/analysistools/${TIER}/${APP}/input_key_prefix"
      - name: OUTPUT_KEY_PREFIX
        valueFrom: "/analysistools/${TIER}/${APP}/output_key_prefix"
      - name: EMAIL_ADMIN
        valueFrom: "/analysistools/${TIER}/${APP}/email_admin"
      - name: EMAIL_SMTP_HOST
        valueFrom: "/analysistools/${TIER}/${APP}/email_smtp_host"
      - name: EMAIL_SMTP_PORT
        valueFrom: "/analysistools/${TIER}/${APP}/email_smtp_port"
      - name: VPC_ID
        valueFrom: "/analysistools/${TIER}/${APP}/vpc_id"
      - name: SUBNET_IDS
        valueFrom: "/analysistools/${TIER}/${APP}/subnet_ids"
      - name: SECURITY_GROUP_IDS
        valueFrom: "/analysistools/${TIER}/${APP}/security_group_ids"
      - name: ECS_CLUSTER
        valueFrom: "/analysistools/${TIER}/${APP}/ecs_cluster"
      - name: WORKER_TASK_NAME
        valueFrom: "/analysistools/${TIER}/${APP}/ecs_worker_task"
      - name: REFITTING_WORKER_TASK_NAME
        valueFrom: "/analysistools/${TIER}/${APP}/ecs_refitting_worker_task"
      - name: POSTGRES_HOST
        valueFrom: "/analysistools/${TIER}/${APP}/postgres_host"
      - name: POSTGRES_PORT
        valueFrom: "/analysistools/${TIER}/${APP}/postgres_port"
      - name: POSTGRES_USER
        valueFrom: "/analysistools/${TIER}/${APP}/postgres_user"
      - name: POSTGRES_PASS
        valueFrom: "/analysistools/${TIER}/${APP}/postgres_pass"
      - name: POSTGRES_DB
        valueFrom: "/analysistools/${TIER}/${APP}/postgres_db"
      - name: BATCH_COMPUTE_ENVIRONMENT
        valueFrom: "/analysistools/${TIER}/${APP}/batch_compute_environment"
      - name: BATCH_JOB_QUEUE
        valueFrom: "/analysistools/${TIER}/${APP}/batch_job_queue"
      - name: BATCH_JOB_DEFINITION
        valueFrom: "/analysistools/${TIER}/${APP}/batch_job_definition"
      - name: EXTRACTION_FORM_LIMIT
        valueFrom: "/analysistools/${TIER}/${APP}/extraction_form_limit"
    mountPoints:
      - sourceVolume: data
        containerPath: "/data"
        readOnly: false
    logConfiguration:
      logDriver: awsfirelens
      options:
        Name: datadog
        tls: "on"
        tls.verify: "off"
        dd_service: "${TIER}-${APP}-backend"
        dd_source: "nodejs"
        dd_tags: "project:${APP} tier:${TIER}"
        provider: ecs
      secretOptions:
        - name: Host
          valueFrom: /analysistools/${TIER}/datadog/log_endpoint_host
        - name: apikey
          valueFrom: /analysistools/${TIER}/datadog/api_key
tags:
  - key: Project
    value: "${APP}"
  - key: ApplicationName
    value: "${APP}"
  - key: ResourceName
    value: "${TIER}-${APP}-web-ecs-task"
  - key: EnvironmentTier
    value: "${ENVIRONMENT_TIER}"
  - key: ResourceFunction
    value: compute
  - key: Creator
    value: TF
