name: Deploy msigportal-dev
on: 
  push:
    branches:
      - '*-dev'
  workflow_dispatch:

jobs:
  Deploy:
    environment: Dev Deployment
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: List files in the repository
        run: ls ${{ github.workspace }}
        
      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: 'javascript'
          queries: security-and-quality

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
