name: Deploy msigportal-dev
on: 
  push:
    branches:
      - '*-dev'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: List files in the repository
        run: ls ${{ github.workspace }}

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: 'javascript'
          queries: security-and-quality

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
        
      - name: Build backend image
        run: |
          DOCKER_BUILDKIT=1
          MSIGPORTAL_BACKEND_IMAGE=msigportal-backend

          docker build \
            -t $MSIGPORTAL_BACKEND_IMAGE \
            -f docker/backend.dockerfile \
            .
